### PR TITLE
Fixed "Unknown prop" warning among other minor tweaks

### PR DESCRIPTION
**Pull request by hugofelp**
- included local copy of eslint to enable consistent testing
- made onClose callback optional
- filtered component own properties from div to avoid "Unknown prop" warning  #14 

If you're happy with the changes, would you care to update the package on npm?
Thanks a lot.

### CODE REVIEW

**Comment by zackify** [comment]
Thanks a lot for the pull request and adding es lint! I've been keeping up with the latest ideas on fixing the prop warning. I think we should go ahead and accept a new prop, domProps. And just spread ...this.props.domProps. That would mean no filtering. But also a major version change. Anything not specific to the component would be passed in as an object to domProps. What do you think? Dan Abramov suggested this idea on twitter. If you like it, add it and I'll add a new release ASAP.

**Comment by hugofelp** [comment]
That is indeed a good idea, but as you pointed out it will be a breaking change, potentially breaking apps that inadvertently update the dependency. What if we kept the filter as it is, for backwards compatibility, and also included this new property as a the recommended way of passing DOM props? You could then drop support to the old filter on a future major release...

**Comment by hugofelp** [comment]
Or, just save this idea of a new prop altogether for a future major release? thoughts?

**Comment by zackify** [comment]
Hmm, I guess I will go ahead and merge it. Then will make a new major
release with the idea I have. Instead of just making a new major right
away.

**Pull request merged**
